"""
Models for quiz application.
"""

from django.db import models
from django.contrib.auth.models import User


class Quiz(models.Model):
    """
    Quiz model representing a quiz generated from a YouTube video.

    Attributes:
        user: Foreign key to User who created the quiz
        title: Quiz title (generated by AI, editable)
        description: Quiz description (generated by AI, editable)
        video_url: YouTube video URL used for quiz generation
        created_at: Timestamp when quiz was created
        updated_at: Timestamp when quiz was last updated
    """

    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='quizzes',
        help_text="User who created this quiz"
    )
    title = models.CharField(
        max_length=200,
        help_text="Quiz title"
    )
    description = models.TextField(
        help_text="Quiz description"
    )
    video_url = models.URLField(
        help_text="YouTube video URL"
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
        help_text="Creation timestamp"
    )
    updated_at = models.DateTimeField(
        auto_now=True,
        help_text="Last update timestamp"
    )

    class Meta:
        ordering = ['-created_at']
        verbose_name_plural = 'Quizzes'

    def __str__(self):
        return f"{self.title} - {self.user.username}"


class Question(models.Model):
    """
    Question model representing a single quiz question.

    Each quiz has exactly 10 questions with 4 options each.

    Attributes:
        quiz: Foreign key to parent Quiz
        question_title: The question text
        question_options: JSON array of 4 answer options
        answer: The correct answer (must be one of the options)
        created_at: Timestamp when question was created
        updated_at: Timestamp when question was last updated
    """

    quiz = models.ForeignKey(
        Quiz,
        on_delete=models.CASCADE,
        related_name='questions',
        help_text="Parent quiz"
    )
    question_title = models.CharField(
        max_length=500,
        help_text="Question text"
    )
    question_options = models.JSONField(
        help_text="Array of 4 answer options"
    )
    answer = models.CharField(
        max_length=200,
        help_text="Correct answer"
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
        help_text="Creation timestamp"
    )
    updated_at = models.DateTimeField(
        auto_now=True,
        help_text="Last update timestamp"
    )

    class Meta:
        ordering = ['id']

    def __str__(self):
        return f"{self.quiz.title} - Q{self.id}"
